name: README Info Update

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mahyarmirrashed/action-github-readme-stats@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Europe/Berlin"
          FEATURES: "DAY_STATS,WEEK_STATS"
